name: Python Homework Autograder

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  grading:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Setup virtualenv and dependencies
        run: |
          uv venv
          .venv/bin/uv sync

      - name: Run pytest for functional correctness
        run: .venv/bin/pytest tests/test_hw.py

      - name: Run type checks with mypy
        run: .venv/bin/mypy src/main.py

      - name: Check formatting with black
        run: .venv/bin/black --check src/

      - name: Run custom AST checks (e.g. must use recursion)
        run: .venv/bin/python scripts/ast_check.py

      - name: Run output format tests
        run: .venv/bin/python scripts/output_format_test.py

      - name: (Optional) Compute score
        run: .venv/bin/python scripts/compute_score.py