name: Python Homework Autograder

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  grading:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create and activate virtualenv
        run: |
          uv venv
          echo "source .venv/bin/activate" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv sync

      - name: Run pytest for functional correctness
        run: |
          source .venv/bin/activate
          pytest tests/test_hw.py

      - name: Run type checks with mypy
        run: |
          source .venv/bin/activate
          mypy src/main.py

      - name: Check formatting with black
        run: |
          source .venv/bin/activate
          black --check src/

      - name: Run custom AST checks (e.g. must use recursion)
        run: |
          source .venv/bin/activate
          python scripts/ast_check.py

      - name: Run output format tests
        run: |
          source .venv/bin/activate
          python scripts/output_format_test.py

      - name: (Optional) Compute score
        run: |
          source .venv/bin/activate
          python scripts/compute_score.py